on:
  push:
    tags:
      - "*"
name: Release Build
jobs:
  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Build zip file
        run: zip -r "bedrock-bone-meal-${{ github.ref_name }}.zip" .
        working-directory: bedrock-bone-meal
      - name: Release
        uses: softprops/action-gh-release@v0.1.7
        with:
          generate_release_notes: true
          discussion_category_name: 'Announcements'
          files: ./bedrock-bone-meal/*.zip
